language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8
env:
  global:
    - secure: "m/KNJfq9tstauNAf/VJ53DbTaAZxjUggH3Mm9hxNbMGqOYce1cUbMsFlZ2id\nWSRXwdGWHd9uVm9OBUHVCLuIdhd8nTHuQIOgVkcX88CxBvHq4Vbk6s6/yakl\nieJSv11Yj1J2tGlTu96BktfXk7j63K2SYnnbG0hP+LDzi8Kdpd4="
    - secure: "P7QuOF/SHlWyIdpkIMV9gzLBZMYzlYjNUk6ZIxVKbTql1uRy/OoErhSykr1K\nzwaMzbOKU/CF/y1bebQPdRxRkG1jydLkHGHlowbsGE/VWM6X1G+GxIcRcQR6\nHvF4aPdfJ/RIf9qMTHRr3tW60vyIxGIqDLncB12oBAALOt91u60="